### PR TITLE
Update main.py for Python2 and Python3 user input support

### PR DESCRIPTION
**Pull request by rmccorm4**
Add support for both Python2/Python3 rather than asking user to manually change the code as suggested in this comment: # If you can't use Python 3.x, please change "input" to "raw_input"

### CODE REVIEW

**Comment by erickoledadevrel** [comment]
Thanks for the contribution? Looks like they are some linting errors reported by Travis. Can you please resolve those?

**Comment by rmccorm4** [comment]
Yes sorry, had to run to a meeting before checking the Travis results. Turns out most accepted methods go against "redefining builtin input", so I used `six.moves.input()` instead to keep Python2/Python3 support.

**Comment by erickoledadevrel** [comment]
Awesome, thanks for doing the work to find a compatible solution. Should the `six` package be added to the install instructions in the README? I think it's a dependency of the Google API Client library, but probably not safe to rely on that.

**Comment by rmccorm4** [comment]
I ran it inside of a Docker container that only installs python and pip, and then does `pip3 install google-api-python-client oauth2client` - **So it should be okay without it**. It wouldn't hurt to add it to the README, but that's up to you.

**Pull request merged**
