### PR TITLE
Consolidate redundant variables of quickstart.py

### PR DESCRIPTION
**Pull request by tai271828**
SAMPLE_RANGE_NAME is not used at all in the current code. Use it to remove duplicate *Class Data!A2:E*.

### CODE REVIEW

**Comment by tai271828** [comment]
I signed CLA.

**Comment by erickoledadevrel** [comment]
Thanks for catching this! I think a better solution would be to just use that variable, and SAMPLE_SPREADSHEET_ID, directly:

```
result = service.spreadsheets().values().get(spreadsheetId=SAMPLE_SPREADSHEET_ID,
                                             range=SAMPLE_RANGE_NAME).execute()
```

**Comment by tai271828** [comment]
Thanks for the review. Fixed the PR and rebased the branch. Besides, I included not only *SAMPLE_RANGE_NAME* but also *SAMPLE_SPREADSHEET_ID*. It is ready to review again now.

**Comment by tai271828** [comment]
pylint check does not pass. Fixing.

**Comment by tai271828** [comment]
OK. Ready to review now! Thanks!

**Pull request merged**
